#!/usr/bin/env python3
"""Validate a tag-submission pull request.

Usage: validate_tags.py <base_sha> <head_sha>

A submission is "benign" only if, relative to the base:
  - it ONLY *adds* files (no edits/deletes/renames of existing files), and
  - every added file is either a `tags/data/<stem>.r2tag.zip` or its matching
    `tags/data/<stem>.json` sidecar, and
  - each .r2tag.zip contains exactly one `*.r2tag` entry that is a real GVAS
    save within size limits (guards against junk / zip bombs / path traversal),
  - each sidecar is well-formed and points back at its zip.

index.json is generated by build_tags_manifest.py, never submitted directly.
Exits non-zero (with a ::error:: annotation) on the first problem.
"""
import json
import os
import re
import subprocess
import sys
import zipfile

MAX_ZIP_BYTES = 512 * 1024          # the uploaded .r2tag.zip
MAX_INNER_BYTES = 2 * 1024 * 1024   # decompressed .r2tag (a full save is < 1 MB)
NAME_MAX = 64
AUTHOR_MAX = 64

ALLOWED_RE = re.compile(r'^tags/data/[^/]+\.(r2tag\.zip|json)$')
ZIP_RE = re.compile(r'^tags/data/(.+)\.r2tag\.zip$')
SIDE_RE = re.compile(r'^tags/data/(.+)\.json$')


def fail(msg):
    print(f"::error::{msg}")
    sys.exit(1)


def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def main():
    if len(sys.argv) != 3:
        fail("usage: validate_tags.py <base_sha> <head_sha>")
    base, head = sys.argv[1], sys.argv[2]

    diff = git("diff", "--name-status", base, head).strip()
    if not diff:
        fail("No file changes detected in this PR.")

    zips, sidecars = {}, {}
    for line in diff.splitlines():
        parts = line.split("\t")
        status, path = parts[0], parts[-1]

        if status[0] != "A":
            fail(f"Only new files may be added; '{path}' has status '{status}'. "
                 "Submissions must not modify or delete existing files.")
        if not ALLOWED_RE.match(path):
            fail(f"'{path}' is outside the allowed set (tags/data/*.r2tag.zip + sidecar).")
        if path == "tags/data/index.json":
            fail("index.json is generated automatically — don't include it in a submission.")

        m = ZIP_RE.match(path)
        if m:
            zips[m.group(1)] = path
            continue
        m = SIDE_RE.match(path)
        if m:
            sidecars[m.group(1)] = path

    if not zips:
        fail("No .r2tag.zip files were added.")
    if set(zips) != set(sidecars):
        missing = (set(zips) ^ set(sidecars))
        fail(f"Each .r2tag.zip needs a matching .json sidecar (and vice versa). Mismatch: {sorted(missing)}")

    for stem, path in zips.items():
        validate_zip(stem, path)
    for stem, path in sidecars.items():
        validate_sidecar(stem, path)

    print(f"OK: {len(zips)} tag submission(s) validated.")


def validate_zip(stem, path):
    size = os.path.getsize(path)
    if size > MAX_ZIP_BYTES:
        fail(f"{path}: zip is {size} bytes (> {MAX_ZIP_BYTES} limit).")
    try:
        zf = zipfile.ZipFile(path)
    except zipfile.BadZipFile:
        fail(f"{path}: not a valid zip archive.")

    members = [n for n in zf.namelist() if not n.endswith("/")]
    if len(members) != 1:
        fail(f"{path}: zip must contain exactly one file, found {len(members)}.")
    inner = members[0]
    if "/" in inner or "\\" in inner or ".." in inner:
        fail(f"{path}: zip entry '{inner}' has an unsafe path.")
    if not inner.lower().endswith(".r2tag"):
        fail(f"{path}: inner file '{inner}' must be a .r2tag.")

    info = zf.getinfo(inner)
    if info.file_size > MAX_INNER_BYTES:
        fail(f"{path}: decompressed entry is {info.file_size} bytes (> {MAX_INNER_BYTES} limit).")

    with zf.open(inner) as f:
        magic = f.read(4)
    if magic != b"GVAS":
        fail(f"{path}: inner file is not a GVAS save (bad magic {magic!r}).")


def validate_sidecar(stem, path):
    try:
        data = json.load(open(path, encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        fail(f"{path}: invalid JSON ({e}).")
    if not isinstance(data, dict):
        fail(f"{path}: sidecar must be a JSON object.")

    name = data.get("name")
    author = data.get("author", "")
    file = data.get("file")

    if not isinstance(name, str) or not (1 <= len(name) <= NAME_MAX):
        fail(f"{path}: 'name' must be a string of 1-{NAME_MAX} chars.")
    if not isinstance(author, str) or len(author) > AUTHOR_MAX:
        fail(f"{path}: 'author' must be a string up to {AUTHOR_MAX} chars.")
    if file != f"{stem}.r2tag.zip":
        fail(f"{path}: 'file' must be '{stem}.r2tag.zip', got {file!r}.")
    if any(ord(c) < 32 for c in name + author):
        fail(f"{path}: 'name'/'author' contain control characters.")


if __name__ == "__main__":
    main()
